create table community_comment_collection_targets (
    id bigint generated by default as identity primary key,
    post_id bigint,
    source varchar(40) not null,
    external_id varchar(200) not null,
    board_id varchar(120),
    trigger_reason varchar(40) not null,
    triggered_at datetime(6) not null,
    max_comments integer not null,
    priority integer not null default 100,
    view_count integer,
    recommend_count integer,
    comment_count integer,
    status varchar(40) not null default 'PENDING',
    crawl_run_id varchar(160),
    created_at datetime(6) not null,
    updated_at datetime(6) not null,
    constraint uk_comment_target_source_external unique (source, external_id),
    constraint fk_comment_target_post foreign key (post_id) references community_posts (id) on delete cascade
);

create index idx_comment_target_status_priority_created
    on community_comment_collection_targets (status, priority, created_at);

create index idx_comment_target_source_created
    on community_comment_collection_targets (source, created_at);
